import React,{useEffect,useMemo,useRef,useState}from"react";
import{ArrowLeft,Brush,Check,ChevronRight,Eraser,Heart,HelpCircle,Map,Pencil,RotateCcw,Star,Trash2,Undo2,UserRoundPen,Volume2,Zap}from"lucide-react";
const STORAGE="matematikmastarna-profiles-v1",ACTIVE="matematikmastarna-active-profile";
const HEROES=[{id:"nova",name:"Nova",icon:"🧙"},{id:"max",name:"Max",icon:"🦸"},{id:"lumi",name:"Lumi",icon:"🧝"},{id:"rex",name:"Rex",icon:"🥷"}];
const WORLDS=[{id:1,title:"Talbyggaren",sub:"Addition",icon:"🏰",op:"add"},{id:2,title:"Lånebergen",sub:"Subtraktion",icon:"⛰️",op:"sub"},{id:3,title:"Multiplikationsskogen",sub:"Multiplikation",icon:"🌲",op:"mul"},{id:4,title:"Divisionstemplet",sub:"Division",icon:"🏛️",op:"div"},{id:5,title:"Decimalriket",sub:"Addition och subtraktion",icon:"💎",op:"decimal"}];
const LEVELS={support:{name:"Träna",icon:"🌱"},base:{name:"Utmaning",icon:"🌿"},expert:{name:"Expert",icon:"🔥"}};
const rnd=(a,b)=>Math.floor(Math.random()*(b-a+1))+a,fmt=n=>new Intl.NumberFormat("sv-SE").format(n);
const decimal=v=>{let w=Math.floor(v/100),f=String(v%100).padStart(2,"0").replace(/0+$/g,"");return f?`${w},${f}`:`${w}`};
const parseDec=s=>{s=String(s).replace(",",".");if(!/^\d+(\.\d{0,2})?$/.test(s))return null;let[a,b=""]=s.split(".");return +a*100+ +(b.padEnd(2,"0"))};
function problem(op,level,n){let a,b,answer,remainder=0,symbol="+";const p=Math.min(4,Math.ceil(n/3));if(op==="decimal"){let minus=p>2;a=rnd(level==="support"?110:120,level==="expert"?9999:4999);b=rnd(10,Math.max(11,Math.min(a-1,3499)));if(minus&&b>a)[a,b]=[b,a];return{op,symbol:minus?"−":"+",a,b,answer:minus?a-b:a+b,displayA:decimal(a),displayB:decimal(b),displayAnswer:decimal(minus?a-b:a+b)}}if(op==="add"){a=rnd(20,level==="expert"?4999:499);b=rnd(8,level==="expert"?3999:399);answer=a+b}else if(op==="sub"){a=rnd(level==="support"?30:120,level==="expert"?9999:999);b=rnd(10,a-1);answer=a-b;symbol="−"}else if(op==="mul"){a=rnd(12,level==="expert"?999:299);b=rnd(2,level==="support"?9:level==="expert"?99:29);answer=a*b;symbol="×"}else{b=rnd(2,level==="expert"?35:12);answer=rnd(2,level==="expert"?250:99);if(level!=="support"&&p===4)remainder=rnd(1,b-1);a=b*answer+remainder;symbol="÷"}return{op,a,b,answer,remainder,symbol}}
const Button=({children,className="",...p})=><button className={`btn ${className}`} {...p}>{children}</button>;
function Canvas({reset}){
  const c=useRef(),box=useRef(),down=useRef(false),last=useRef(),hist=useRef([]),offset=useRef({x:0,y:0});
  const[tool,setTool]=useState("pen"),[undoable,setUndoable]=useState(false),[zoom,setZoom]=useState(1),[mode,setMode]=useState("draw");
  const white=()=>{let x=c.current?.getContext("2d");if(x){x.fillStyle="white";x.fillRect(0,0,c.current.width,c.current.height)}};
  const applyView=()=>{if(box.current){box.current.style.setProperty("--zoom",zoom);box.current.style.setProperty("--pan-x",`${offset.current.x}px`);box.current.style.setProperty("--pan-y",`${offset.current.y}px`)}};
  useEffect(applyView,[zoom]);
  useEffect(()=>{const resize=()=>{let el=c.current,r=box.current?.getBoundingClientRect();if(!el||!r)return;let snap=el.width?el.toDataURL():null,d=devicePixelRatio||1,canvasHeight=innerWidth<760?360:500;el.width=Math.max(280,r.width)*d;el.height=canvasHeight*d;el.style.width="100%";el.style.height=`${canvasHeight}px`;white();if(snap){let i=new Image;i.onload=()=>el.getContext("2d").drawImage(i,0,0,el.width,el.height);i.src=snap}};resize();let ro=new ResizeObserver(resize);ro.observe(box.current);return()=>ro.disconnect()},[]);
  useEffect(()=>{white();hist.current=[];setUndoable(false);setZoom(1);setMode("draw");offset.current={x:0,y:0};applyView()},[reset]);
  const pos=e=>{let r=c.current.getBoundingClientRect();return{x:(e.clientX-r.left)*c.current.width/r.width,y:(e.clientY-r.top)*c.current.height/r.height}};
  const start=e=>{e.preventDefault();e.currentTarget.setPointerCapture?.(e.pointerId);down.current=true;last.current=mode==="pan"?{x:e.clientX,y:e.clientY}:pos(e);if(mode==="draw"){hist.current.push(c.current.toDataURL());setUndoable(true)}};
  const move=e=>{if(!down.current)return;e.preventDefault();if(mode==="pan"){offset.current={x:offset.current.x+(e.clientX-last.current.x),y:offset.current.y+(e.clientY-last.current.y)};last.current={x:e.clientX,y:e.clientY};applyView();return}let x=c.current.getContext("2d"),p=pos(e),d=devicePixelRatio||1;x.beginPath();x.moveTo(last.current.x,last.current.y);x.lineTo(p.x,p.y);x.lineCap="round";x.strokeStyle=tool==="pen"?"#172033":"white";x.lineWidth=(tool==="pen"?4:28)*d;x.stroke();last.current=p};
  const stop=e=>{down.current=false;if(e.currentTarget.hasPointerCapture?.(e.pointerId))e.currentTarget.releasePointerCapture(e.pointerId)};
  const clear=()=>{white();hist.current=[];setUndoable(false)};
  const undo=()=>{let src=hist.current.pop();if(!src)return;let i=new Image;i.onload=()=>{white();c.current.getContext("2d").drawImage(i,0,0,c.current.width,c.current.height)};i.src=src;setUndoable(hist.current.length>0)};
  const changeZoom=step=>{setZoom(z=>{let next=Math.min(1.5,Math.max(.75,Math.round((z+step)*4)/4));if(next===1)offset.current={x:0,y:0};return next})};
  const resetView=()=>{setZoom(1);offset.current={x:0,y:0};applyView()};
  return <div className="canvas-card"><div className="canvas-tools"><span><Button onClick={()=>{setMode("draw");setTool("pen")}} className={mode==="draw"&&tool==="pen"?"active":""}><Pencil/>Penna</Button><Button onClick={()=>{setMode("draw");setTool("eraser")}} className={mode==="draw"&&tool==="eraser"?"active":""}><Eraser/>Sudd</Button><Button onClick={()=>setMode("pan")} className={mode==="pan"?"active":""}>✋ Flytta</Button></span><span className="zoom-tools"><Button onClick={()=>changeZoom(-.25)} disabled={zoom<=.75}>−</Button><Button onClick={resetView}>{Math.round(zoom*100)} %</Button><Button onClick={()=>changeZoom(.25)} disabled={zoom>=1.5}>+</Button><Button disabled={!undoable} onClick={undo}><Undo2/></Button><Button onClick={clear}><Trash2/></Button></span></div><div ref={box} className={`canvas-wrap ${mode==="pan"?"pan-mode":"draw-mode"}`}><div className="canvas-stage"><canvas ref={c} onPointerDown={start} onPointerMove={move} onPointerUp={stop} onPointerCancel={stop}/></div></div></div>
}
function Profiles({profiles,setProfiles,setActive,setScreen}){const[name,setName]=useState(""),[hero,setHero]=useState("nova");const create=()=>{let n=name.trim().slice(0,20);if(!n)return;let id=`p-${Date.now()}`;setProfiles(x=>[...x,{id,name:n,heroId:hero,stats:{xp:0,lives:5,streak:0,bestStreak:0,worldResults:{}}}]);setActive(id);setScreen("map")};return <main className="start"><h1>🏰 Matematikmästarna</h1><div className="panel"><h2>{profiles.length?"Välj elevprofil":"Skapa elevprofil"}</h2>{profiles.map(p=><div className="profile" key={p.id}><Button onClick={()=>{setActive(p.id);setScreen("map")}}>{HEROES.find(h=>h.id===p.heroId)?.icon} {p.name} · {p.stats.xp} XP</Button><Button onClick={()=>setProfiles(x=>x.filter(y=>y.id!==p.id))}><Trash2/></Button></div>)}<input value={name} onChange={e=>setName(e.target.value)} placeholder="Elevens namn"/><div className="heroes">{HEROES.map(h=><Button key={h.id} className={hero===h.id?"active":""} onClick={()=>setHero(h.id)}>{h.icon} {h.name}</Button>)}</div><Button className="primary wide" onClick={create}>Skapa profil och börja <ChevronRight/></Button></div></main>}
function App(){const[profiles,setProfiles]=useState([]),[active,setActive]=useState(null),[screen,setScreen]=useState("profiles"),[world,setWorld]=useState(1),[level,setLevel]=useState("base");useEffect(()=>{try{setProfiles(JSON.parse(localStorage.getItem(STORAGE)||"[]"));setActive(localStorage.getItem(ACTIVE))}catch{}},[]);useEffect(()=>{localStorage.setItem(STORAGE,JSON.stringify(profiles));active?localStorage.setItem(ACTIVE,active):localStorage.removeItem(ACTIVE)},[profiles,active]);let profile=profiles.find(p=>p.id===active);const stats=fn=>setProfiles(ps=>ps.map(p=>p.id===active?{...p,stats:fn(p.stats)}:p));if(screen==="profiles"||!profile)return <Profiles {...{profiles,setProfiles,setActive,setScreen}}/>;return <><header><Button onClick={()=>setScreen("map")}>{HEROES.find(h=>h.id===profile.heroId)?.icon} {profile.name}</Button><span><Heart/> {profile.stats.lives} <Zap/> {profile.stats.streak} <Star/> {profile.stats.xp}</span><Button onClick={()=>setScreen("profiles")}><UserRoundPen/>Byt spelare</Button></header>{screen==="map"&&<MapScreen profile={profile} open={id=>{setWorld(id);setScreen("level")}}/>}{screen==="level"&&<Level world={world} back={()=>setScreen("map")} pick={l=>{setLevel(l);stats(s=>({...s,lives:5,streak:0}));setScreen("game")}}/>}{screen==="game"&&<Game key={`${active}-${world}-${level}`} profile={profile} world={world} level={level} stats={stats} exit={()=>setScreen("level")} map={()=>setScreen("map")}/>}</>}
function MapScreen({profile,open}){return <main><h1><Map/> Världskarta</h1><div className="worlds">{WORLDS.map(w=>{let r=profile.stats.worldResults?.[w.id];return <button className={`world w${w.id}`} key={w.id} onClick={()=>open(w.id)}><b>{w.icon} {w.title}</b><small>{w.sub}</small>{r?<span>Senast {r.latestCorrect}/12 · Bäst {r.bestCorrect}/12</span>:<span>Inget resultat ännu</span>}</button>})}</div></main>}
function Level({world,back,pick}){let w=WORLDS.find(x=>x.id===world);return <main><Button onClick={back}><ArrowLeft/>Världskartan</Button><h1>{w.icon} {w.title}</h1><div className="levels">{Object.entries(LEVELS).map(([k,l])=><button key={k} onClick={()=>pick(k)}><b>{l.icon} {l.name}</b><span>{k==="support"?"Mindre tal och tydliga ledtrådar.":k==="base"?"Skriftlig metod och lagom utmaning.":"Större tal och mindre stöd."}</span></button>)}</div></main>}
function Game({profile,world,level,stats,exit,map}){
  let w=WORLDS.find(x=>x.id===world);
  const[n,setN]=useState(1),[p,setP]=useState(()=>problem(w.op,level,1)),[answer,setAnswer]=useState(""),[rest,setRest]=useState(""),[field,setField]=useState("answer"),[correct,setCorrect]=useState(0),[attempts,setAttempts]=useState(0),[hints,setHints]=useState(0),[hint,setHint]=useState(""),[reset,setReset]=useState(0),[feedback,setFeedback]=useState(null),[done,setDone]=useState(false);
  const read=()=>{if(!("speechSynthesis" in window))return;let word=p.symbol==="+"?"plus":p.symbol==="−"?"minus":p.symbol==="×"?"gånger":"delat med",a=w.op==="decimal"?p.displayA.replace(","," komma "):p.a,b=w.op==="decimal"?p.displayB.replace(","," komma "):p.b,u=new SpeechSynthesisUtterance(`Uppgift ${n}. ${a} ${word} ${b}. ${w.op==="decimal"?"Skriv svaret med decimaltecken.":""}`);u.lang="sv-SE";u.rate=.88;speechSynthesis.cancel();speechSynthesis.speak(u)};
  useEffect(()=>()=>speechSynthesis?.cancel?.(),[]);
  const showHint=()=>{if(!hint)setHints(x=>x+1);setHint(w.op==="decimal"?"Placera decimaltecknen under varandra.":w.op==="div"?"Tänk baklänges med multiplikation.":"Börja med entalen och kontrollera varje steg.")};
  const press=k=>{let set=field==="rest"?setRest:setAnswer;if(k==="Rensa")return set("");if(k==="⌫")return set(v=>v.slice(0,-1));set(v=>{if(k===","&&v.includes(","))return v;if(w.op==="decimal"&&v.includes(",")&&v.split(",")[1].length>=2)return v;return(v+String(k)).slice(0,7)})};
  const submit=()=>{let ok=(w.op==="decimal"?parseDec(answer):+answer)===p.answer&&(w.op!=="div"||+(rest||0)===p.remainder);setAttempts(x=>x+1);if(ok){setCorrect(x=>x+1);stats(s=>({...s,xp:s.xp+10,streak:s.streak+1,bestStreak:Math.max(s.bestStreak,s.streak+1)}));setFeedback(true)}else{stats(s=>({...s,lives:Math.max(0,s.lives-1),streak:0}));setFeedback(false)}};
  const next=()=>{if(n===12){let totalCorrect=correct+1,totalAttempts=Math.max(1,attempts),accuracy=Math.round(totalCorrect/totalAttempts*100),old=profile.stats.worldResults?.[world]||{};stats(s=>({...s,worldResults:{...(s.worldResults||{}),[world]:{...old,plays:(old.plays||0)+1,latestCorrect:totalCorrect,bestCorrect:Math.max(old.bestCorrect||0,totalCorrect),latestAccuracy:accuracy,bestAccuracy:Math.max(old.bestAccuracy||0,accuracy)}}}));setCorrect(totalCorrect);setDone(true);return}let q=n+1;setN(q);setP(problem(w.op,level,q));setAnswer("");setRest("");setHint("");setFeedback(null);setReset(x=>x+1)};
  if(done)return <main><div className="panel summary"><h1>🎉 Bra kämpat, {profile.name}!</h1><h2>{correct}/12 rätt</h2><p>Försök: {attempts} · Ledtrådar: {hints}</p><p>Träna vidare genom att förklara hur du kontrollerar ditt svar.</p><Button className="primary" onClick={()=>location.reload()}><RotateCcw/>Spela igen</Button><Button onClick={exit}>Annan nivå</Button><Button onClick={map}><Map/>Världskartan</Button></div></main>;
  let keys=w.op==="decimal"?[1,2,3,4,5,6,7,8,9,",",0,"⌫","Rensa"]:[1,2,3,4,5,6,7,8,9,"Rensa",0,"⌫"];
  const task=<><div className="task-heading"><span>{w.icon}</span><div><small>UPPGIFT {n} AV 12</small><h2>{w.title}</h2></div></div><div className="task-expression">{w.op==="decimal"?p.displayA:fmt(p.a)} {p.symbol} {w.op==="decimal"?p.displayB:fmt(p.b)}</div><div className="task-actions"><Button onClick={read}><Volume2/>Läs upp</Button><Button onClick={showHint}><HelpCircle/>Ledtråd</Button></div>{hint&&<p className="hint">{hint}</p>}</>;
  return <main className="play-main"><Button onClick={exit}><ArrowLeft/>Byt nivå</Button><div className="progress"><i style={{width:`${n/12*100}%`}}/></div><div className="play-layout"><aside className={`task-panel w${world}`}>{task}<div className="answer compact"><button onClick={()=>setField("answer")} className={field==="answer"?"selected":""}><small>{w.op==="div"?"KVOT":`${profile.name.toUpperCase()}S SVAR`}</small><b>{answer||"?"}</b></button>{w.op==="div"&&<button onClick={()=>setField("rest")} className={field==="rest"?"selected":""}><small>REST</small><b>{rest||"0"}</b></button>}<div className="keys">{keys.map(k=><button className={k==="Rensa"&&w.op==="decimal"?"span3":""} key={k} onClick={()=>press(k)}>{k}</button>)}</div><Button className="primary wide" disabled={!answer} onClick={submit}>Kontrollera <Check/></Button></div></aside><section className="work-panel"><h2><Brush/>Skrivyta</h2><p className="work-help">Skriv uppställningen med finger eller penna. Använd Flytta när du har zoomat in.</p><Canvas reset={reset}/></section></div>{feedback!==null&&<div className="modal"><div><h1>{feedback?"🎉 Bra jobbat!":"💪 Försök igen!"}</h1>{feedback?<Button className="primary wide" onClick={next}>Nästa uppgift <ChevronRight/></Button>:<Button className="primary wide" onClick={()=>{setFeedback(null);setAnswer("");setRest("")}}>Försök igen</Button>}</div></div>}</main>
}
export default App;