import React,{useEffect,useMemo,useRef,useState}from"react";
const KEY="matematikmastarna-provtraning-kap1-v2";
const SKILLS={place:{name:"Tal och platsvärde",icon:"🔢"},ten:{name:"10, 100 och 1 000",icon:"↔️"},mul:{name:"Multiplikation med decimaler",icon:"✖️"},div:{name:"Division med decimaler",icon:"➗"},large:{name:"Stora tal och smarta strategier",icon:"🧠"},problem:{name:"Problemlösning och rimlighet",icon:"🧩"}};
const Q=(id,skill,prompt,answer,options,hint,explain)=>({id,skill,prompt,answer,options,hint,explain,type:options?"choice":"input"});
const START=[
Q("d1","place","Vilket tal är störst?","0",["-3","0","-7"],"Titta på tallinjen.","0 ligger till höger om negativa tal."),
Q("d2","place","Vilket värde har siffran 6 i 4 062,15?","60",["6","60","600"],"6 står på tiotalsplatsen.","Siffran 6 har värdet 60."),
Q("d3","ten","1,45 × 100 =","145",null,"Varje siffra blir hundra gånger mer värd.","1,45 × 100 = 145."),
Q("d4","ten","62,4 ÷ 100 =","0,624",null,"Varje siffra blir en hundradel så mycket värd.","62,4 ÷ 100 = 0,624."),
Q("d5","mul","0,7 × 2,4 =","1,68",null,"Räkna 7 × 24 och placera två decimaler.","7 × 24 = 168, alltså 1,68."),
Q("d6","mul","Vilket svar är rimligt för 30 × 1,6?","48",["4,8","48","480"],"30 × 2 är 60.","30 × 1,6 = 48."),
Q("d7","div","6,3 ÷ 5 =","1,26",null,"Skriv 6,30 och fortsätt divisionen.","6,3 ÷ 5 = 1,26."),
Q("d8","div","14,5 ÷ 10 =","1,45",null,"Varje siffra blir en tiondel så mycket värd.","14,5 ÷ 10 = 1,45."),
Q("d9","large","0,11 × 400 =","44",null,"Tänk 0,11 × 4 × 100.","0,11 × 400 = 44."),
Q("d10","large","325 ÷ 50 =","6,5",null,"Förkorta båda talen med 10.","32,5 ÷ 5 = 6,5."),
Q("d11","problem","En vara kostar 24 kr per hektogram. Vad kostar 6 kg? Svara i kronor.","1440",null,"6 kg är 60 hektogram.","60 × 24 = 1 440 kr."),
Q("d12","problem","62 400 vingslag per minut är ungefär hur många per sekund?","1 000",["100","1 000","10 000"],"En minut har 60 sekunder.","62 400 ÷ 60 = 1 040, ungefär 1 000.")];
const TRAIN={
place:[Q("p1","place","Vilket tecken passar? -2 __ 3","<",["<",">","="],"-2 ligger till vänster om 3.","-2 < 3."),Q("p2","place","Värdet av siffran 7 i 5 741,2?","700",null,"7 står på hundratalsplatsen.","7 × 100 = 700."),Q("p3","place","Vilket tal är 4 hundratal, 2 tiotal och 6 ental?","426",null,"400 + 20 + 6.","Talet är 426."),Q("p4","place","Vilket tal ligger närmast 0?","-1",["-6","-1","4"],"Jämför avstånden till 0.","-1 ligger närmast."),Q("p5","place","Vilket tal är udda?","305",["128","305","640"],"Udda tal slutar på 1,3,5,7 eller 9.","305 är udda.")],
ten:[Q("t1","ten","3,28 × 10 =","32,8",null,"Tio gånger större.","Svaret är 32,8."),Q("t2","ten","0,46 × 1 000 =","460",null,"Multiplicera med 10 tre gånger.","Svaret är 460."),Q("t3","ten","875 ÷ 100 =","8,75",null,"Hundra gånger mindre.","Svaret är 8,75."),Q("t4","ten","4,2 ÷ 1 000 =","0,0042",null,"Tänk 4,200.","Svaret är 0,0042."),Q("t5","ten","Vilket är störst?","De är lika",["0,52 × 10","52 ÷ 10","De är lika"],"Räkna båda.","Båda är 5,2.")],
mul:[Q("m1","mul","0,6 × 2,5 =","1,5",null,"6 × 25 = 150.","Två decimaler ger 1,50."),Q("m2","mul","1,4 × 0,3 =","0,42",null,"Svaret ska vara mindre än 1,4.","14 × 3 = 42, alltså 0,42."),Q("m3","mul","2,3 × 0,4 =","0,92",["9,2","0,92","0,092"],"Två decimaler sammanlagt.","Svaret är 0,92."),Q("m4","mul","1,25 × 8 =","10",null,"125 hundradelar × 8.","Svaret är 10."),Q("m5","mul","Vilken produkt är störst?","0,8 × 50",["0,8 × 50","4 × 9","De är lika"],"Räkna eller uppskatta.","40 är större än 36.")],
div:[Q("v1","div","7,2 ÷ 6 =","1,2",null,"72 tiondelar delat med 6.","Svaret är 1,2."),Q("v2","div","9,45 ÷ 5 =","1,89",null,"Fortsätt till hundradelar.","Svaret är 1,89."),Q("v3","div","48 ÷ 60 =","0,8",null,"Förkorta med 10.","4,8 ÷ 6 = 0,8."),Q("v4","div","735 ÷ 50 =","14,7",null,"73,5 ÷ 5.","Svaret är 14,7."),Q("v5","div","Rimligt svar för 12,6 ÷ 3?","4,2",["0,42","4,2","42"],"12 ÷ 3 är cirka 4.","Svaret är 4,2.")],
large:[Q("l1","large","70 × 600 =","42000",null,"Börja med 7 × 6.","Tre nollor ger 42 000."),Q("l2","large","0,08 × 500 =","40",null,"0,08 × 5 × 100.","Svaret är 40."),Q("l3","large","84 ÷ 40 =","2,1",null,"8,4 ÷ 4.","Svaret är 2,1."),Q("l4","large","61,2 ÷ 90 =","0,68",null,"6,12 ÷ 9.","Svaret är 0,68."),Q("l5","large","Jämför produkterna.","De är lika",["0,75 × 64 000","0,64 × 75 000","De är lika"],"Räkna båda eller jämför faktorerna.","Båda är 48 000.")],
problem:[Q("s1","problem","50 pennor kostar 145 kr. Pris per penna?","2,9",null,"Dividera totalpriset med 50.","145 ÷ 50 = 2,90 kr."),Q("s2","problem","150 meter på 2 minuter. Hur långt på 10 minuter?","750",null,"10 minuter är fem gånger längre.","150 × 5 = 750 meter."),Q("s3","problem","0,38 gram styck. Ungefär vad väger 200 stycken?","80 gram",["8 gram","80 gram","800 gram"],"0,38 är ungefär 0,4.","0,4 × 200 = 80."),Q("s4","problem","40 km fram och tillbaka under 10 dagar. Hur långt enkel väg?","2",null,"Först per dag, sedan halvera.","40 ÷ 10 ÷ 2 = 2 km."),Q("s5","problem","62 400 per minut är ungefär ... per sekund.","1 000",["100","1 000","10 000"],"Dividera med 60.","Det blir ungefär 1 000.")]};
const norm=v=>String(v??"").trim().toLowerCase().replace(/\s/g,"").replace(".",",");
const right=(q,v)=>norm(q.answer)===norm(v);
function Speak({text}){return <button className="pt-ghost" onClick={()=>{speechSynthesis.cancel();let u=new SpeechSynthesisUtterance(text.replaceAll("×"," gånger ").replaceAll("÷"," delat med ").replaceAll(","," komma "));u.lang="sv-SE";u.rate=.88;speechSynthesis.speak(u)}}>🔊 Läs upp</button>}
function Canvas({reset}){const ref=useRef(),on=useRef(false),last=useRef();useEffect(()=>{let c=ref.current;c?.getContext("2d").clearRect(0,0,c.width,c.height)},[reset]);let p=e=>{let r=ref.current.getBoundingClientRect();return{x:(e.clientX-r.left)*ref.current.width/r.width,y:(e.clientY-r.top)*ref.current.height/r.height}};return <section className="pt-canvas"><div><b>Rita och räkna</b><button onClick={()=>ref.current.getContext("2d").clearRect(0,0,900,600)}>Rensa</button></div><canvas ref={ref} width="900" height="600" onPointerDown={e=>{on.current=true;last.current=p(e);e.currentTarget.setPointerCapture?.(e.pointerId)}} onPointerMove={e=>{if(!on.current)return;let n=p(e),x=ref.current.getContext("2d");x.beginPath();x.moveTo(last.current.x,last.current.y);x.lineTo(n.x,n.y);x.strokeStyle="#14224f";x.lineWidth=4;x.lineCap="round";x.stroke();last.current=n}} onPointerUp={()=>on.current=false}/></section>}
function Question({q,index,total,value,setValue,onSave,training=false,feedback,onHint,reset}){return <div className="pt-layout"><section className="pt-card"><small>UPPGIFT {index+1} AV {total}</small><Speak text={`${q.prompt}. ${q.options?.join(". ")||""}`}/><h1>{q.prompt}</h1>{q.type==="choice"?<div className="pt-options">{q.options.map(x=><button className={value===x?"selected":""} onClick={()=>setValue(x)} key={x}>{x}</button>)}</div>:<input autoFocus inputMode="decimal" value={value} onChange={e=>setValue(e.target.value)} placeholder="Skriv ditt svar"/>}{training&&<button className="pt-hint" onClick={onHint}>💡 Ledtråd</button>}{feedback&&<div className={feedback.ok?"pt-feedback ok":"pt-feedback think"}><b>{feedback.ok?"Rätt!":"Tänk en gång till"}</b><p>{feedback.text}</p></div>}<button className="pt-primary" disabled={!value} onClick={onSave}>{training?feedback?.ok?"Nästa uppgift":"Kontrollera":"Spara svar"}</button></section><Canvas reset={reset}/></div>}
function analyze(qs,answers){let a={};Object.keys(SKILLS).forEach(k=>a[k]={right:0,total:0});qs.forEach(q=>{a[q.skill].total++;if(right(q,answers[q.id]))a[q.skill].right++});Object.values(a).forEach(x=>x.percent=Math.round(x.right/x.total*100));return a}
export default function ProvtraningKapitel1({profile,onBack}){let id=profile?.id||"local",saved=useMemo(()=>{try{return JSON.parse(localStorage.getItem(`${KEY}-${id}`)||"{}")}catch{return{}}},[id]);const[screen,setScreen]=useState(saved.screen||"intro"),[index,setIndex]=useState(saved.index||0),[answers,setAnswers]=useState(saved.answers||{}),[analysis,setAnalysis]=useState(saved.analysis||null),[plan,setPlan]=useState(saved.plan||[]),[planIndex,setPlanIndex]=useState(0),[value,setValue]=useState(""),[feedback,setFeedback]=useState(null),[reset,setReset]=useState(0),[mockAnswers,setMockAnswers]=useState({});useEffect(()=>localStorage.setItem(`${KEY}-${id}`,JSON.stringify({screen,index,answers,analysis,plan})),[screen,index,answers,analysis,plan,id]);
const diagnosticSave=()=>{let q=START[index],next={...answers,[q.id]:value};setAnswers(next);setValue("");setReset(x=>x+1);if(index===11){let a=analyze(START,next);setAnalysis(a);setScreen("analysis")}else setIndex(i=>i+1)};
const startPlan=()=>{let p=Object.entries(analysis).sort((a,b)=>a[1].percent-b[1].percent).slice(0,3).map(x=>x[0]);setPlan(p);setPlanIndex(0);setIndex(0);setFeedback(null);setScreen("training")};let skill=plan[planIndex],trainQ=TRAIN[skill]?.[index];
const trainSave=()=>{if(feedback?.ok){setFeedback(null);setValue("");setReset(x=>x+1);if(index===4){if(planIndex===plan.length-1){setIndex(0);setScreen("recheck")}else{setPlanIndex(i=>i+1);setIndex(0)}}else setIndex(i=>i+1);return}let ok=right(trainQ,value);setFeedback({ok,text:ok?trainQ.explain:trainQ.hint})};
const recheck=useMemo(()=>plan.flatMap(k=>TRAIN[k].slice(0,2)).map((q,i)=>({...q,id:`r${i}`})),[plan]);const[reAnswers,setReAnswers]=useState({});const reSave=()=>{let q=recheck[index],next={...reAnswers,[q.id]:value};setReAnswers(next);setValue("");setReset(x=>x+1);if(index===recheck.length-1)setScreen("reResult");else setIndex(i=>i+1)};
const mock=useMemo(()=>[...START,...Object.values(TRAIN).flat().filter((_,i)=>i%4===0)].slice(0,18).map((q,i)=>({...q,id:`m${i}`})),[]);const mockSave=()=>{let q=mock[index],next={...mockAnswers,[q.id]:value};setMockAnswers(next);setValue("");setReset(x=>x+1);if(index===mock.length-1)setScreen("mockResult");else setIndex(i=>i+1)};
const Result=({qs,ans,title,next})=>{let count=qs.filter(q=>right(q,ans[q.id])).length,a=analyze(qs,ans),weak=Object.entries(a).sort((x,y)=>x[1].percent-y[1].percent).slice(0,3);return <div className="pt-page"><section className="pt-result"><span>🏆</span><small>{title}</small><h1>{count} av {qs.length} rätt</h1><h2>🎯 Träna vidare på</h2>{weak.map(([k])=><p key={k}>• {SKILLS[k].name}</p>)}<button className="pt-primary" onClick={next}>Nästa steg</button><button onClick={()=>setScreen("analysis")}>Till analysen</button></section></div>};
if(screen==="intro")return <div className="pt-page"><button onClick={onBack}>← Tillbaka</button><header className="pt-hero"><span>🏆</span><div><small>TRÄNA INFÖR PROVET</small><h1>Kapitel 1: Tal och räknesätt</h1><p>Startkoll, personlig träning och ett provliknande pass.</p></div></header><div className="pt-steps">{["Startkoll · 12 frågor","Personlig analys","Min träningsplan","Testa dig själv"].map((x,i)=><article key={x}><span>{i+1}</span><b>{x}</b></article>)}</div><button className="pt-start" onClick={()=>{setIndex(0);setAnswers({});setScreen("diagnostic")}}>Starta Startkollen</button>{analysis&&<button className="pt-continue" onClick={()=>setScreen("analysis")}>Fortsätt från analysen</button>}</div>;
if(screen==="diagnostic")return <div className="pt-page"><Question q={START[index]} index={index} total={12} value={value} setValue={setValue} onSave={diagnosticSave} reset={reset}/></div>;
if(screen==="analysis"){let needs=Object.entries(analysis).sort((a,b)=>a[1].percent-b[1].percent).slice(0,3);return <div className="pt-page"><header className="pt-hero"><span>🎯</span><div><small>PERSONLIG ANALYS</small><h1>Din plan inför provet</h1><p>Det här bygger på just Startkollen.</p></div></header><div className="pt-skillgrid">{Object.entries(analysis).map(([k,r])=><article key={k}><span>{SKILLS[k].icon}</span><b>{SKILLS[k].name}</b><small>{r.right} av {r.total} rätt</small><i><em style={{width:`${r.percent}%`}}/></i></article>)}</div><section className="pt-next"><h2>🎯 Ditt nästa steg</h2>{needs.map(([k])=><p key={k}>• {SKILLS[k].name}</p>)}</section><button className="pt-start" onClick={startPlan}>Starta min träning</button><button onClick={()=>{setIndex(0);setMockAnswers({});setScreen("mock")}}>Testa mig själv direkt</button></div>}
if(screen==="training")return <div className="pt-page"><h2>{SKILLS[skill].icon} {SKILLS[skill].name} · Pass {planIndex+1} av {plan.length}</h2><Question q={trainQ} index={index} total={5} value={value} setValue={setValue} onSave={trainSave} training feedback={feedback} onHint={()=>setFeedback({ok:false,text:trainQ.hint})} reset={reset}/></div>;
if(screen==="recheck")return <div className="pt-page"><h2>Ny kort kontroll</h2><Question q={recheck[index]} index={index} total={recheck.length} value={value} setValue={setValue} onSave={reSave} reset={reset}/></div>;
if(screen==="reResult")return <Result qs={recheck} ans={reAnswers} title="Kontroll efter träning" next={()=>{setIndex(0);setMockAnswers({});setScreen("mock")}}/>;
if(screen==="mock")return <div className="pt-page"><h2>Testa dig själv</h2><Question q={mock[index]} index={index} total={mock.length} value={value} setValue={setValue} onSave={mockSave} reset={reset}/></div>;
if(screen==="mockResult")return <Result qs={mock} ans={mockAnswers} title="Testa dig själv" next={()=>setScreen("analysis")}/>;return null}
