import React,{useEffect,useMemo,useRef,useState}from"react";
import"./provtraning-v2.css";

const STORE="matematikmastarna-provtraning-kap1-v2";
const SKILLS={
 place:{name:"Tal och platsvärde",icon:"🔢",foundation:"positionsvärde och tallinje"},
 ten:{name:"10, 100 och 1 000",icon:"↔️",foundation:"hur siffrors värde förändras"},
 mul:{name:"Multiplikation med decimaler",icon:"✖️",foundation:"talfakta och decimalers värde"},
 div:{name:"Division med decimaler",icon:"➗",foundation:"talfamiljer och division"},
 large:{name:"Stora tal och smarta strategier",icon:"🧠",foundation:"nollor, förkortning och uppskattning"},
 problem:{name:"Problemlösning och rimlighet",icon:"🧩",foundation:"välja räknesätt och tolka enheter"}
};
const norm=v=>String(v??"").trim().toLowerCase().replace(/\s/g,"").replace(".",",");
const Q=(id,skill,prompt,answer,{options=null,hint="",explain="",error="metod",level="method",visual=""}={})=>({id,skill,prompt,answer:String(answer),options,hint,explain,error,level,visual,type:options?"choice":"input"});
const correct=(q,v)=>norm(q.answer)===norm(v);

const CORE=[
 Q("c1","place","Vilket tal är störst?","0",{options:["-3","0","-7"],hint:"Titta på en tallinje.",explain:"0 ligger till höger om alla negativa tal.",error:"negativa-tal",level:"foundation"}),
 Q("c2","place","Vilket värde har siffran 6 i 4 062,15?","60",{options:["6","60","600"],hint:"6 står på tiotalsplatsen.",explain:"Siffran 6 har värdet 60.",error:"positionsvärde"}),
 Q("c3","ten","1,45 × 100 =","145",{hint:"Varje siffra blir hundra gånger mer värd.",explain:"1,45 × 100 = 145.",error:"fel-riktning"}),
 Q("c4","ten","62,4 ÷ 100 =","0,624",{hint:"Varje siffra blir en hundradel så mycket värd.",explain:"62,4 ÷ 100 = 0,624.",error:"decimalplacering"}),
 Q("c5","mul","0,7 × 2,4 =","1,68",{hint:"Räkna 7 × 24 och placera två decimaler.",explain:"7 × 24 = 168. Två decimaler ger 1,68.",error:"decimalplacering"}),
 Q("c6","mul","Vilket svar är rimligt för 30 × 1,6?","48",{options:["4,8","48","480"],hint:"30 × 2 är ungefär 60.",explain:"30 × 1,6 = 48.",error:"rimlighet",level:"apply"}),
 Q("c7","div","6,3 ÷ 5 =","1,26",{hint:"Skriv 6,30 och fortsätt divisionen.",explain:"6,3 ÷ 5 = 1,26.",error:"avslutar-för-tidigt"}),
 Q("c8","div","14,5 ÷ 10 =","1,45",{hint:"Talet blir tio gånger mindre.",explain:"14,5 ÷ 10 = 1,45.",error:"decimalplacering"}),
 Q("c9","large","0,11 × 400 =","44",{hint:"Tänk 0,11 × 4 × 100.",explain:"0,11 × 4 = 0,44 och 0,44 × 100 = 44.",error:"nollor"}),
 Q("c10","large","325 ÷ 50 =","6,5",{hint:"Förkorta båda talen med 10.",explain:"32,5 ÷ 5 = 6,5.",error:"förkortning"}),
 Q("c11","problem","En vara kostar 24 kr per hektogram. Vad kostar 6 kg?","1440",{hint:"6 kg är 60 hektogram.",explain:"60 × 24 = 1 440 kr.",error:"enhetsomvandling",level:"apply"}),
 Q("c12","problem","62 400 vingslag per minut är ungefär hur många per sekund?","1 000",{options:["100","1 000","10 000"],hint:"En minut har 60 sekunder.",explain:"62 400 ÷ 60 = 1 040, ungefär 1 000.",error:"rimlighet",level:"reason"})
];
const FOLLOW={
 place:Q("f-place","place","Vilket tal ligger närmast 0?","-1",{options:["-6","-1","4"],hint:"Jämför avståndet till noll.",explain:"-1 är ett steg från 0.",error:"negativa-tal",level:"foundation"}),
 ten:Q("f-ten","ten","8,3 ÷ 10 =","0,83",{hint:"Talet blir tio gånger mindre.",explain:"8,3 ÷ 10 = 0,83.",error:"decimalplacering"}),
 mul:Q("f-mul","mul","0,6 × 4 =","2,4",{hint:"6 tiondelar × 4 = 24 tiondelar.",explain:"24 tiondelar är 2,4.",error:"talfakta",level:"foundation"}),
 div:Q("f-div","div","7,2 ÷ 6 =","1,2",{hint:"72 tiondelar ÷ 6.",explain:"12 tiondelar är 1,2.",error:"talfamilj",level:"foundation"}),
 large:Q("f-large","large","70 × 600 =","42000",{hint:"Börja med 7 × 6.",explain:"42 och tre nollor blir 42 000.",error:"nollor"}),
 problem:Q("f-problem","problem","150 meter på 2 minuter. Hur långt på 10 minuter?","750",{hint:"10 minuter är fem gånger så lång tid.",explain:"150 × 5 = 750 meter.",error:"proportionalitet",level:"apply"})
};

const LESSONS={
 place:{title:"Siffrans plats bestämmer värdet",steps:["I talet 4 062 står 6 på tiotalsplatsen.","6 tiotal är 60.","På tallinjen är talet längst till höger störst."],example:"4 062 = 4 000 + 60 + 2"},
 ten:{title:"Gör varje siffra mer eller mindre värd",steps:["× 10 gör värdet tio gånger större.","÷ 10 gör värdet tio gånger mindre.","Använd positionsvärdet, inte bara en regel om kommatecknet."],example:"3,2 × 10 = 32   och   3,2 ÷ 10 = 0,32"},
 mul:{title:"Talfakta först, decimalens värde sedan",steps:["Räkna först som om talen vore heltal.","Kontrollera hur stort svaret bör vara.","Placera decimaltecknet så att svaret blir rimligt."],example:"0,6 × 4 = 24 tiondelar = 2,4"},
 div:{title:"Division och multiplikation hör ihop",steps:["Använd talfamiljen för att kontrollera.","Skriv en nolla efter decimalen om divisionen behöver fortsätta.","Kontrollera med multiplikation."],example:"7,2 ÷ 6 = 1,2 eftersom 1,2 × 6 = 7,2"},
 large:{title:"Förenkla utan att ändra svaret",steps:["Använd grundfaktan.","Håll reda på nollor och positionsvärde.","I division kan båda talen delas med samma tal."],example:"84 ÷ 40 = 8,4 ÷ 4 = 2,1"},
 problem:{title:"Läs, välj, räkna och kontrollera",steps:["Markera vad du vet och vad frågan söker.","Välj räknesätt och kontrollera enheten.","Uppskatta för att se om svaret är rimligt."],example:"6 kg = 60 hg. 60 × 24 kr = 1 440 kr"}
};

function seeded(seed,min,max){let x=Math.sin(seed*999)*10000;return min+Math.floor((x-Math.floor(x))*(max-min+1))}
function generate(skill,tier,i){let n=i+1,a=seeded(n+tier.length,2,9),b=seeded(n*3+tier.charCodeAt(0),2,8);
 if(skill==="place")return tier==="foundation"?Q(`g-${skill}-${tier}-${i}`,skill,`Vilket värde har siffran ${a} i talet ${a}42?`,String(a*100),{hint:`${a} står på hundratalsplatsen.`,explain:`${a} × 100 = ${a*100}.`,error:"positionsvärde",level:tier}):Q(`g-${skill}-${tier}-${i}`,skill,`Vilket tal är störst?`,String(a),{options:[String(-a),String(a),String(a-1)],hint:"Talet längst till höger på tallinjen är störst.",explain:`${a} är störst.`,error:"tallinje",level:tier});
 if(skill==="ten"){let d=`${a},${b}`;let mult=tier==="foundation"?10:tier==="method"?100:1000;return Q(`g-${skill}-${tier}-${i}`,skill,`${d} ${i%2?"÷":"×"} ${mult} =`,i%2?String(Number(d.replace(",","."))/mult).replace(".",","):String(Number(d.replace(",","."))*mult).replace(".",","),{hint:i%2?"Talet ska bli mindre.":"Talet ska bli större.",explain:"Använd positionsvärdet steg för steg.",error:"decimalplacering",level:tier})}
 if(skill==="mul"){let x=(a/10),ans=x*b;return Q(`g-${skill}-${tier}-${i}`,skill,`${String(x).replace(".",",")} × ${b} =`,String(ans).replace(".",","),{hint:`Börja med ${a} × ${b}.`,explain:`${a} tiondelar × ${b} = ${a*b} tiondelar.`,error:"decimalplacering",level:tier})}
 if(skill==="div"){let ans=a/10,total=ans*b;return Q(`g-${skill}-${tier}-${i}`,skill,`${String(total).replace(".",",")} ÷ ${b} =`,String(ans).replace(".",","),{hint:`Använd ${b} × ? = ${String(total).replace(".",",")}.`,explain:`Svaret är ${String(ans).replace(".",",")}.`,error:"talfamilj",level:tier})}
 if(skill==="large"){let x=a*10,y=b*100,ans=x*y;return Q(`g-${skill}-${tier}-${i}`,skill,`${x} × ${y} =`,String(ans),{hint:`Börja med ${a} × ${b}.`,explain:`Grundfaktan är ${a*b} och faktorerna har tre nollor.`,error:"nollor",level:tier})}
 let rate=a*10,count=b,ans=rate*count;return Q(`g-${skill}-${tier}-${i}`,skill,`En låda kostar ${rate} kr. Vad kostar ${count} lådor?`,String(ans),{hint:"Multiplicera priset med antalet lådor.",explain:`${rate} × ${count} = ${ans} kr.`,error:"fel-räknesätt",level:tier})
}
const buildSet=(skill,startTier,count=8)=>{let tiers=startTier==="foundation"?["foundation","foundation","method","method","apply","apply","reason","mixed"]:startTier==="method"?["method","method","method","apply","apply","reason","mixed","mixed"]:["apply","apply","reason","reason","mixed","mixed","mixed","mixed"];return tiers.slice(0,count).map((t,i)=>generate(skill,t,i))};

function speak(text){if(!("speechSynthesis"in window))return;speechSynthesis.cancel();let u=new SpeechSynthesisUtterance(String(text).replaceAll("×"," gånger ").replaceAll("÷"," delat med ").replaceAll("="," är lika med ").replaceAll(","," komma "));u.lang="sv-SE";u.rate=.88;speechSynthesis.speak(u)}
function Pad({reset}){const r=useRef(),on=useRef(false),last=useRef();useEffect(()=>{let c=r.current;c?.getContext("2d").clearRect(0,0,c.width,c.height)},[reset]);let p=e=>{let b=r.current.getBoundingClientRect();return{x:(e.clientX-b.left)*r.current.width/b.width,y:(e.clientY-b.top)*r.current.height/b.height}};return <section className="pv2-pad"><header><b>Rita och räkna</b><button onClick={()=>r.current.getContext("2d").clearRect(0,0,1000,700)}>Rensa</button></header><canvas ref={r} width="1000" height="700" onPointerDown={e=>{on.current=true;last.current=p(e);e.currentTarget.setPointerCapture?.(e.pointerId)}} onPointerMove={e=>{if(!on.current)return;let n=p(e),x=r.current.getContext("2d");x.beginPath();x.moveTo(last.current.x,last.current.y);x.lineTo(n.x,n.y);x.strokeStyle="#172554";x.lineWidth=4;x.lineCap="round";x.stroke();last.current=n}} onPointerUp={()=>on.current=false}/></section>}
function Question({q,index,total,value,setValue,onSubmit,training,feedback,onHint,reset,label="UPPGIFT"}){return <div className="pv2-layout"><section className="pv2-question"><small>{label} · {index+1} AV {total}</small><button className="pv2-listen" onClick={()=>speak(`${q.prompt}. ${q.options?.join(". ")||""}`)}>🔊 Läs upp</button><h1>{q.prompt}</h1>{q.visual&&<div className="pv2-visual">{q.visual}</div>}{q.options?<div className="pv2-options">{q.options.map(o=><button key={o} className={value===o?"selected":""} onClick={()=>setValue(o)}>{o}</button>)}</div>:<input inputMode="decimal" value={value} onChange={e=>setValue(e.target.value)} placeholder="Skriv ditt svar"/>}{training&&<button className="pv2-hint" onClick={onHint}>💡 Visa en ledtråd</button>}{feedback&&<div className={`pv2-feedback ${feedback.ok?"ok":"think"}`}><b>{feedback.ok?"Rätt!":"Försök en gång till"}</b><p>{feedback.text}</p></div>}<button className="pv2-primary" disabled={!String(value).trim()} onClick={onSubmit}>{training&&feedback?.ok?"Nästa uppgift":"Kontrollera"}</button></section><Pad reset={reset}/></div>}
function analyse(qs,answers){let r={};Object.keys(SKILLS).forEach(k=>r[k]={right:0,total:0,errors:{}});qs.forEach(q=>{r[q.skill].total++;if(correct(q,answers[q.id]))r[q.skill].right++;else r[q.skill].errors[q.error]=(r[q.skill].errors[q.error]||0)+1});Object.values(r).forEach(x=>x.percent=x.total?Math.round(x.right/x.total*100):0);return r}
function levelFor(r){return r.percent<40?"foundation":r.percent<70?"method":"apply"}
function statusFor(r){return r.percent<40?"Börja med grunden":r.percent<70?"Under utveckling":r.percent<80?"På god väg":"Säker inför provet"}

export default function ProvtraningKapitel1({profile,onBack}){let id=profile?.id||"local",saved=useMemo(()=>{try{return JSON.parse(localStorage.getItem(`${STORE}-${id}`)||"{}")}catch{return{}}},[id]);const[view,setView]=useState(saved.view||"intro"),[index,setIndex]=useState(saved.index||0),[answers,setAnswers]=useState(saved.answers||{}),[sequence,setSequence]=useState(CORE),[analysis,setAnalysis]=useState(saved.analysis||null),[plan,setPlan]=useState(saved.plan||[]),[planIndex,setPlanIndex]=useState(saved.planIndex||0),[trainingSet,setTrainingSet]=useState([]),[value,setValue]=useState(""),[feedback,setFeedback]=useState(null),[reset,setReset]=useState(0),[reAnswers,setReAnswers]=useState({}),[mixedAnswers,setMixedAnswers]=useState({}),[mockAnswers,setMockAnswers]=useState({});useEffect(()=>{try{localStorage.setItem(`${STORE}-${id}`,JSON.stringify({view,index,answers,analysis,plan,planIndex}))}catch{}},[view,index,answers,analysis,plan,planIndex,id]);
 const finishCore=next=>{let a=analyse(CORE,next),follow=Object.entries(a).filter(([,r])=>r.right===1).map(([k])=>FOLLOW[k]);if(follow.length){setSequence([...CORE,...follow]);setIndex(12)}else{setAnalysis(a);setView("analysis")}};
 const saveDiagnostic=()=>{let q=sequence[index],next={...answers,[q.id]:value};setAnswers(next);setValue("");setReset(x=>x+1);if(index===11)finishCore(next);else if(index===sequence.length-1){setAnalysis(analyse(sequence,next));setView("analysis")}else setIndex(x=>x+1)};
 const beginPlan=()=>{let chosen=Object.entries(analysis).sort((a,b)=>a[1].percent-b[1].percent).slice(0,3).map(([skill,r])=>({skill,tier:levelFor(r)}));setPlan(chosen);setPlanIndex(0);setTrainingSet(buildSet(chosen[0].skill,chosen[0].tier));setIndex(0);setFeedback(null);setView("lesson")};
 const startPass=()=>{setIndex(0);setValue("");setFeedback(null);setView("training")};
 const submitTraining=()=>{let q=trainingSet[index];if(feedback?.ok){setFeedback(null);setValue("");setReset(x=>x+1);if(index===trainingSet.length-1){if(planIndex===plan.length-1){setIndex(0);setView("recheck")}else{let next=planIndex+1;setPlanIndex(next);setTrainingSet(buildSet(plan[next].skill,plan[next].tier));setView("lesson")}}else setIndex(x=>x+1);return}let ok=correct(q,value);setFeedback({ok,text:ok?q.explain:q.hint||"Titta på modellen och försök igen."})};
 const recheck=useMemo(()=>plan.flatMap(({skill})=>buildSet(skill,"apply",3)).slice(0,9),[plan]);
 const saveRecheck=()=>{let q=recheck[index],next={...reAnswers,[q.id]:value};setReAnswers(next);setValue("");setReset(x=>x+1);if(index===recheck.length-1){setIndex(0);setView("mixed")}else setIndex(x=>x+1)};
 const mixed=useMemo(()=>Object.keys(SKILLS).flatMap((s,i)=>buildSet(s,"mixed",2).map((q,j)=>({...q,id:`mix-${i}-${j}`}))).slice(0,8),[]);
 const saveMixed=()=>{let q=mixed[index],next={...mixedAnswers,[q.id]:value};setMixedAnswers(next);setValue("");setReset(x=>x+1);if(index===mixed.length-1){setIndex(0);setView("ready")}else setIndex(x=>x+1)};
 const mock=useMemo(()=>[...CORE,...Object.keys(SKILLS).flatMap((s,i)=>buildSet(s,"apply",2).map((q,j)=>({...q,id:`mock-${i}-${j}`})))].slice(0,24),[]);
 const saveMock=()=>{let q=mock[index],next={...mockAnswers,[q.id]:value};setMockAnswers(next);setValue("");setReset(x=>x+1);if(index===mock.length-1)setView("result");else setIndex(x=>x+1)};
 const resetAll=()=>{setView("intro");setIndex(0);setAnswers({});setSequence(CORE);setAnalysis(null);setPlan([]);setFeedback(null);try{localStorage.removeItem(`${STORE}-${id}`)}catch{}};
 if(view==="intro")return <main className="pv2-page"><button className="pv2-back" onClick={onBack}>← Tillbaka</button><header className="pv2-hero"><span>🏆</span><div><small>PROVTRÄNING 2.0</small><h1>Kapitel 1: Tal och räknesätt</h1><p>Spelet kartlägger, undervisar, tränar och kontrollerar vad du har lärt dig.</p></div></header><div className="pv2-steps">{[["1","Adaptiv Startkoll","12–18 frågor"],["2","Minilektioner","Se hur metoden fungerar"],["3","Personlig träning","Tre prioriterade områden"],["4","Kontroll och blandning","Visa vad du kan själv"],["5","Testa dig själv","24 provliknande frågor"]].map(x=><article key={x[0]}><span>{x[0]}</span><b>{x[1]}</b><p>{x[2]}</p></article>)}</div><button className="pv2-start" onClick={()=>{setSequence(CORE);setIndex(0);setAnswers({});setValue("");setView("diagnostic")}}>Starta Startkollen</button>{analysis&&<button className="pv2-secondary" onClick={()=>setView("analysis")}>Fortsätt från min analys</button>}</main>;
 if(view==="diagnostic")return <main className="pv2-page"><Question q={sequence[index]} index={index} total={sequence.length} value={value} setValue={setValue} onSubmit={saveDiagnostic} reset={reset} label="STARTKOLL"/></main>;
 if(view==="analysis"){let ordered=Object.entries(analysis).sort((a,b)=>a[1].percent-b[1].percent);return <main className="pv2-page"><header className="pv2-hero"><span>🎯</span><div><small>PERSONLIG ANALYS</small><h1>Din väg till provet</h1><p>Resultatet beskriver Startkollen. Du får arbeta vidare steg för steg.</p></div></header><div className="pv2-analysis">{ordered.map(([k,r])=><article key={k} className={`status-${levelFor(r)}`}><span>{SKILLS[k].icon}</span><div><b>{SKILLS[k].name}</b><small>{r.right} av {r.total} rätt · {statusFor(r)}</small><i><em style={{width:`${r.percent}%`}}/></i>{Object.keys(r.errors).length>0&&<p>Fokus: {Object.keys(r.errors).join(", ").replaceAll("-"," ")}</p>}</div></article>)}</div><button className="pv2-start" onClick={beginPlan}>Fortsätt min rekommenderade träning</button><button className="pv2-secondary" onClick={()=>{setIndex(0);setView("mock")}}>Testa mig själv direkt</button></main>}
 if(view==="lesson"){let item=plan[planIndex],l=LESSONS[item.skill];return <main className="pv2-page"><div className="pv2-lesson"><small>MINILEKTION · PASS {planIndex+1} AV {plan.length}</small><span>{SKILLS[item.skill].icon}</span><h1>{l.title}</h1><div className="pv2-lesson-steps">{l.steps.map((x,i)=><p key={x}><b>{i+1}</b>{x}</p>)}</div><pre>{l.example}</pre><button onClick={()=>speak(`${l.title}. ${l.steps.join(". ")}. Exempel: ${l.example}`)}>🔊 Läs upp minilektionen</button><button className="pv2-start" onClick={startPass}>Börja träna</button></div></main>}
 if(view==="training")return <main className="pv2-page"><div className="pv2-passhead"><small>PERSONLIG TRÄNING · PASS {planIndex+1} AV {plan.length}</small><h2>{SKILLS[plan[planIndex].skill].icon} {SKILLS[plan[planIndex].skill].name}</h2></div><Question q={trainingSet[index]} index={index} total={trainingSet.length} value={value} setValue={setValue} onSubmit={submitTraining} training feedback={feedback} onHint={()=>setFeedback({ok:false,text:trainingSet[index].hint})} reset={reset} label="TRÄNING"/></main>;
 if(view==="recheck")return <main className="pv2-page"><div className="pv2-passhead"><small>KONTROLL EFTER STÖD</small><h2>Visa vad du kan själv</h2></div><Question q={recheck[index]} index={index} total={recheck.length} value={value} setValue={setValue} onSubmit={saveRecheck} reset={reset} label="KONTROLL"/></main>;
 if(view==="mixed")return <main className="pv2-page"><div className="pv2-passhead"><small>BLANDAD REPETITION</small><h2>Välj metod själv</h2></div><Question q={mixed[index]} index={index} total={mixed.length} value={value} setValue={setValue} onSubmit={saveMixed} reset={reset} label="BLANDAT"/></main>;
 if(view==="ready")return <main className="pv2-page"><div className="pv2-result"><span>🌟</span><h1>Träningsplanen är klar</h1><p>Du har fått undervisning, tränat och gjort nya kontrolluppgifter.</p><button className="pv2-start" onClick={()=>{setIndex(0);setView("mock")}}>Starta Testa dig själv</button><button className="pv2-secondary" onClick={()=>setView("analysis")}>Se analysen igen</button></div></main>;
 if(view==="mock")return <main className="pv2-page"><div className="pv2-passhead"><small>TESTA DIG SJÄLV</small><h2>Provliknande pass · inga ledtrådar</h2></div><Question q={mock[index]} index={index} total={mock.length} value={value} setValue={setValue} onSubmit={saveMock} reset={reset} label="PROVPASS"/></main>;
 if(view==="result"){let a=analyse(mock,mockAnswers),score=mock.filter(q=>correct(q,mockAnswers[q.id])).length;return <main className="pv2-page"><div className="pv2-result"><span>🏆</span><small>TESTA DIG SJÄLV</small><h1>{score} av {mock.length} rätt</h1><div className="pv2-result-grid">{Object.entries(a).map(([k,r])=><article><b>{SKILLS[k].name}</b><span>{statusFor(r)}</span><i><em style={{width:`${r.percent}%`}}/></i></article>)}</div><button className="pv2-start" onClick={()=>setView("analysis")}>Fortsätt träna rekommenderade områden</button><button className="pv2-secondary" onClick={resetAll}>Börja om med en ny Startkoll</button></div></main>};return null}
